version: 2

project_name: excursion-funnel

builds:
  - id: ef
    main: ./cmd/ef
    binary: ef
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  draft: true
